home/urls.py
from unicodedata import name
from django.urls import path
from . import views


urlpatterns = [
    path('home', views.home, name='home'),
    path('about', views.about,name='about'),
    path('contacts', views.contacts,  name='contacts'),
    path('', views.landing, name='landing' ),
    path('lms', views.lms_home, name='lms'),
    path('terms', views.terms_conditions, name='terms'),
    path('policy', views.privacy_policy, name='policy'),
    path('watchlist', views.watchlist, name="watchlist"),
    path('how-it-works', views.how_it_works, name="how_it_works"),
    path('post-project', views.post_project, name="post_project")
    
]

sandbox/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

handler404 = 'home.views.handler404'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),
    path('', include('home.urls')),
    path('', include('talents.urls')),
    path('', include('startups.urls')),
    path('', include('opportunity.urls')),
    path('', include('userauth.urls')),
    path('', include('dashboard.urls')),

    #social logins url
    # path('oauth/', include('social_django.urls', namespace='social')), 


    path('password-reset/',auth_views.PasswordResetView.as_view(
        template_name='auth/password_reset.html'),name='password_reset'),

    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(
        template_name='auth/password_reset_done.html'),name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(
        template_name='auth/password_reset_confirm.html'),name='password_reset_confirm'),

    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='auth/password_reset_complete.html'), name="password_reset_complete"),
]



if settings.DEBUG:
    urlpatterns += static(
         settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

dashboard/models.py
from sre_constants import CATEGORY
from sre_parse import CATEGORIES
from unicodedata import category
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from talents.models import Talent
from opportunity.models import Opportunity
from startups.models import Startup



# Create your models here.


STATUS = (
        ('shortlisted','shortlisted'),
        ('rejected','rejected'),
        ('reviewing','reviewing'),
        ('interviewed','interviewed'),
        ('offergiven','offergiven')
    )
class Matches(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    matched_on = models.DateTimeField(default=datetime.now)
    status = models.CharField(choices=STATUS, max_length=100, default='reviewing')
    opportunity= models.ManyToManyField(Opportunity)
    talent = models.ForeignKey(Talent, on_delete=models.CASCADE, null=True, blank=True)
    startup = models.ForeignKey(User, related_name='owner', on_delete=models.CASCADE,null=True, blank=True)

    def __str__(self):
        return str(self.user)
    

    class Meta:
        verbose_name_plural = 'Matches'

    @property
    def get_rating(self):
        rating = Rating.objects.filter(rating_for=self.talent)

        sum_of_user_rates =  sum(rating.values_list('rating_value', flat=True)) # --> rating for one user filtered above

        all_ratings_to_talent = rating.count()  * 5 # --> getting number of all ratings for a filtered user
        try:
            rates= round(sum_of_user_rates * 5 / all_ratings_to_talent, 1)
        except ZeroDivisionError:
            rates = 0
        return rates


    


class Thread(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    reciever = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reciever')
    created_on = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return f"{str( self.sender)} and {str( self.reciever)}"

class Message(models.Model):
    thread = models.ForeignKey(Thread, on_delete=models.CASCADE, null=True)
    user        = models.ForeignKey(User, verbose_name='sender', null=True, on_delete=models.CASCADE)
    the_message = models.TextField()
    sent_on = models.DateTimeField(default=datetime.now)

    # def __str__(self):
    #     return f"{str( self.thread.sender)},{str( self.thread.reciever)}"



class Rating(models.Model):
    rating_by = models.ForeignKey(User, on_delete=models.CASCADE)
    rating_for =  models.ForeignKey(Talent, on_delete=models.CASCADE)
    rating_date = models.DateTimeField(default=datetime.now)
    rating_value = models.FloatField(max_length=100)
    comments = models.TextField(null=True, blank=True)

    def __str__(self):
        return str(self.rating_for)


class Package_Payment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    package_name = models.ForeignKey('Listing', on_delete=models.CASCADE, null=True)
    posted_opportunity = models.IntegerField()
    amount_paid = models.CharField(max_length=100)
    txt_ref = models.CharField(max_length=255)
    verified = models.BooleanField(default=False)
    date_paid = models.DateTimeField(default=datetime.now)


    def __str__(self):
        return self.user.username
    

CHOICES = (
    ('Yes','Yes'),
     ('No','No')
)
CATEGORIES = (
    ('junior_roles','junior_roles'),
    ('mid_level_roles','mid_level_roles'),
    ('senior_roles','senior_roles')
)
class Listing(models.Model):
    name = models.CharField(max_length=100)
    charge = models.CharField(max_length=100, default=0)
    opportunity_listing = models.CharField(max_length=100,choices=CHOICES, default='No')
    talent_due_deligency = models.CharField(max_length=100, choices=CHOICES, default='No')
    legal = models.CharField(max_length=100,choices=CHOICES, default='No')
    payroll = models.CharField(max_length=100,choices=CHOICES, default='No')
    category = models.CharField(choices=CATEGORIES, max_length=100, null=True)

    def __str__(self):
        return f"{self.name} {self.category}"

startups/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
import opportunity


class Startup(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    name  =  models.CharField(max_length=100)
    size = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    description = models.TextField()
    logo =  models.FileField(upload_to='startup_images')
    registered_on = models.DateTimeField(default=datetime.now)
    category = models.CharField(max_length=100,null=True, blank=True)
    size = models.CharField(max_length=100,null=True, blank=True)
    website = models.URLField(max_length=100,null=True, blank=True)
    followers = models.ManyToManyField(User, related_name='followers', blank=True)
    what_we_offer = models.TextField(null=True, blank=True)
    description = models.TextField()
    def __str__(self):
        return str(self.user)

    @property
    def get_rating(self):
        rating = Startup_Rating.objects.filter(rating_for=self.id)

        sum_of_user_rates =  sum(rating.values_list('rating_value', flat=True)) # --> rating for one user filtered above

        all_ratings_to_talent = rating.count()  * 5 # --> getting number of all ratings for a filtered user
        try:
            rates= round(sum_of_user_rates * 5 / all_ratings_to_talent, 1)
        except ZeroDivisionError:
            rates = 0
        return rates
      

    @property
    def get_required_skills(name):
        skill = Skills_Required.objects.filter(startup=name)
        return skill
    
    @property
    def get_opportunities(name):
        opp = opportunity.models.Opportunity.objects.filter(startup_name=name)
        return opp
    




class Skills_Required(models.Model):
    startup = models.ForeignKey(Startup, on_delete=models.CASCADE)
    skill = models.CharField(max_length=100)


    def __str__(self):
        return self.skill

    class Meta:
        verbose_name_plural = "Skills_Required"



class Startup_Rating(models.Model):
    rating_by = models.ForeignKey(User, on_delete=models.CASCADE)
    rating_for =  models.ForeignKey(Startup, on_delete=models.CASCADE)
    rating_date = models.DateTimeField(default=datetime.now)
    rating_value = models.FloatField(max_length=100)
    comments = models.TextField(null=True, blank=True)

    def __str__(self):
        return str(self.rating_for)

talents/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from django.utils.text import slugify
from hitcount.models import  HitCount
from django.contrib.contenttypes.fields import GenericRelation
import dashboard



# Create your models here.


SECTORS = (
    ('Architecture & Construction','Architecture & Construction'),
    ('Accountancy and Financial Management','Accountancy and Financial Management'),
    ('Business, Consulting and Management','Business, Consulting and Management '),
    ('Law and Legal Services','Law and Legal Services'),
    ('Non Government Organization','Non Government Organization '),
    ('Media and Communications','Media and Communications'),
    ('Creative Arts and Design','Creative Arts and Design'),
    ('Energy and Utilities','Energy and Utilities'),
    ('Engineering and Manufacturing','Engineering and Manufacturing'),
    ('Agribusiness','Agribusiness'),
    ('Medical and Healthcare','Medical and Healthcare'),
    ('Information Technology','Information Technology'),
    ('Hospitality and Tourism','Hospitality and Tourism'),
    ('Marketing, Advertising and PR','Marketing, Advertising and PR'),
    ('Sales','Sales'),
    ('Real Estate','Real Estate'),
    ('Finance, Retail and Banking Services','Finance, Retail and Banking Services'),
    ('Office Management and Human Resources Services','Office Management and Human Resources Services'),
    ('Transportation, Distribution & Logistics','Transportation, Distribution & Logistics')
)

WORK_EXP =(
    ('Less than 1 Year', 'Less than 1 Year'),
    ('2-5 years','2-5 years'),
    ('5-7 years','5-7 years'),
    ('7-10 years', '7-10 years'),
    ('10 years and above', '10 years and above')      
)
GENDER = (
    ('male','male'),
    ('female','female'),
)
JOB_CATEGORIES = (
    ('full time', 'full time'),
    ('remote', 'remote'),
    ('contractual','contractual'),
    ('internship','internship'),
    ('voluntering', 'voluntering'),
    ('freelance','freelance'),
    ('part-time','part-time'),
    ('temporary', 'temporary'),
    ('internship','internship')
)


class Talent(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    views = models.ManyToManyField(User, related_name="views", blank=True)
    profession  = models.CharField(max_length=100)
    about = models.TextField()
    category = models.CharField(max_length=100, choices=SECTORS)
    years_of_experience = models.CharField(max_length=100, choices=WORK_EXP)
    dob = models.DateTimeField(default=datetime.now)
    gender = models.CharField(max_length=10, choices=GENDER)
    languages = models.CharField(max_length=100)
    salary_expectation = models.CharField(max_length=100)
    prefered_work_type = models.CharField(max_length=100,choices=JOB_CATEGORIES)
    phone = models.CharField(max_length=10)
    location = models.CharField(max_length=100)
    linkedIn = models.URLField(null=True, blank=True)
    slug = models.SlugField(default=User, unique=True)
    hit_count_generic = GenericRelation(HitCount, object_id_field='object_pk',
     related_query_name='hit_count_generic_relation')

    

    def save(self, *args, **kwargs):
        self.slug = slugify(self.user.username)
        super(Talent, self).save(*args, **kwargs)

    @property
    def get_skills(user):
        skills = Skill.objects.filter(talent=user)
        return skills
    
    
    @property
    def get_experience(user):
        exp = Experience.objects.filter(talent=user)
        return exp
    
    @property
    def get_education(user):
        edu = Education.objects.filter(talent=user)
        return edu
    
    @property
    def get_award(user):
        awd = Award.objects.filter(talent=user)
        return awd

    
    @property
    def get_rating(self):
        rating =dashboard.models.Rating.objects.filter(rating_for=self.id)

        sum_of_user_rates =  sum(rating.values_list('rating_value', flat=True)) # --> rating for one user filtered above

        all_ratings_to_talent = rating.count()  * 5 # --> getting number of all ratings for a filtered user
        try:
            rates= round(sum_of_user_rates * 5 / all_ratings_to_talent, 1)
        except ZeroDivisionError:
            rates = 0
        return rates

    def __str__(self):
        return self.user.username



# def create_talent(sender, **kwargs):
#     if kwargs['created']:
#        talent = Talent.objects.create(user=kwargs['instance'])
       
# post_save.connect(create_talent, sender=User)


class Experience(models.Model):
    WORKING = (
        ('No','No'),
        ('Yes',"Yes")
    )
    talent = models.ForeignKey(Talent, on_delete=models.CASCADE)
    company_name =  models.CharField(max_length=100)
    start_date = models.DateTimeField(default=datetime.now)
    finish_date = models.DateTimeField(null=True, blank=True)
    still_working = models.CharField(max_length=100, null=True,blank=True, choices=WORKING)
    position = models.CharField(max_length=100)
    details = models.TextField()

    def __str__(self):
        return str(self.talent)


class Education(models.Model):
    talent = models.ForeignKey(Talent, on_delete=models.CASCADE)
    speciality =  models.CharField(max_length=100)
    start_date = models.DateTimeField(default=datetime.now)
    end_date = models.DateTimeField(max_length=100)
    school_name = models.CharField(max_length=100)
    details = models.TextField()

    def __str__(self):
        return str(self.talent)
    
    class Meta:
        verbose_name_plural = 'Education'
    

class Award(models.Model):
    talent = models.ForeignKey(Talent, on_delete=models.CASCADE)
    name =  models.CharField(max_length=100)
    awarded_on = models.DateTimeField(default=datetime.now)
    details = models.TextField()

    def __str__(self):
        return str(self.talent)

class Skill(models.Model):
    talent = models.ForeignKey(Talent, on_delete=models.CASCADE)
    skill = models.CharField(max_length=100)
    experience = models.CharField(max_length=100, null=True,blank=True)

    def __str__(self):
        return str(self.talent)

home/forms.py
from django import forms

class watchlistForm(forms.Form):
    full_name = forms.CharField()
    email = forms.CharField()
    profession = forms.CharField()
    location = forms.CharField()
    career_background = forms.CharField()

home/views.py
import json
from unicodedata import name
from django.http import HttpResponse
from django.shortcuts import render, redirect
from opportunity.models import Opportunity
from .models import Watchlist
from talents.models import Talent
from startups.models import Startup
from dashboard.models import Listing, Package_Payment, Matches


# Create your views here.

def home(request):
    opportunities = Opportunity.objects.all().order_by('-id')[:9]
    startups =  Startup.objects.all().order_by('-id')[:10]
    listings = Listing.objects.all()
    talents = Talent.objects.all()
    matches = Matches.objects.all()

    package = ''
    if request.user.is_authenticated:
       package =  Package_Payment.objects.filter(user=request.user).last()
    
    
    context = {
        'opportunities':opportunities,
        'startups':startups,
        'listings':listings,
        'package':package,
        'talents':talents,
        'matches':matches
        
    }
    return render(request, 'home/home.html', context)


def watchlist(request):
    if request.method == 'POST':
        full_name = request.POST['name']
        email = request.POST['email']
        profession = request.POST['prof']
        location = request.POST['location']
        career_background = request.POST['career']
        response_data = {}
        watchlist= Watchlist(full_name=full_name, email=email, profession=profession,
         location=location,career_background=career_background)
        watchlist.save()
        response_data['success'] = "Information has been succesful submited"
        return HttpResponse(
            json.dumps(response_data),
            content_type='application/json'
        )
      
    return redirect('landing')


def about(request):
    return render(request, 'home/about.html')

def contacts(request):
    return render(request, 'home/contacts.html')


def landing(request):
    return render(request, 'landing/home.html')


def lms_home(request):
    return render(request, 'home/lms_home.html')



def handler404(request, exception):
    return render(request, 'errors/404.html', locals())

def terms_conditions(request):
    return render(request, 'home/terms_conditions.html')

def privacy_policy(request):
    return render(request, 'home/privacy_policy.html')


def how_it_works(request):
    return render(request, 'home/how_it_works.html')


def post_project(request):
    return render(request, 'home/post_project.html')

templates/dash/followers.html
{% extends 'dash/main.html' %}

{% load static %}

{% block contents %}

<div class="pcoded-inner-content">
    <!-- Main-body start -->
    <div class="main-body">
        <div class="page-wrapper">
            <!-- Page-body start -->
            <div class="page-body">
              <div class="row">
                  <div class="col-md-7">
                    <div class="card table-card">
                        <div class="card-header">
                            <h5>Followers <span class="badge badge-pill badge-warning">{{ followers.count}}</span></h5>
                            <div class="card-header-right">
                                <ul class="list-unstyled card-option">
                                    <li><i class="fa fa fa-wrench open-card-option"></i></li>
                                    <li><i class="fa fa-window-maximize full-card"></i></li>
                                    <li><i class="fa fa-minus minimize-card"></i></li>
                                    <li><i class="fa fa-refresh reload-card"></i></li>
                                    <li><i class="fa fa-trash close-card"></i></li>
                                </ul>
                            </div>
                        </div>
                        <div class="card-block">
                            <div class="table-responsive">
                                <table class="table table-hover m-b-0" >
                                    <thead  >
                                        <th class="font-weight-bold" >Name</th>
                                        <th class="font-weight-bold">Registered As</th>
                                        <th class="font-weight-bold" >Rating Average</th>
                                    </thead>
                                    <tbody>
                                        {% for data in follows %}
                                        <tr>
                                            <td>
                                                <div class="d-inline-block align-middle">
                                                    <img src="{{ data.profile.image.url }}" alt="user image" class="img-radius img-40 align-top m-r-15">
                                                    <div class="d-inline-block">
                                                        <h6>
                                                            {% if data.profile.user_type == 'talent' %}
                                                            {% for data in data.talent_set.all %}
                                                            <a href="{% url 'talent_details' data.slug %}" >
                                                                {% endfor %}
                                                                {% if data.first_name and data.last_name %}
                                                                    {{ data.first_name }} {{ data.last_name }}
                                                                {% else %}
                                                                    {{data.username}}
                                                                {% endif %}
                                                            </a>
                                                            {% elif data.profile.user_type == 'startup' %}
                                                                {% for data in data.startup_set.all %}
                                                                    <a href="{% url 'startup_details' data.id %}" >
                                                                {% endfor %}
                                                                {% if data.first_name and data.last_name %}
                                                                    {{ data.first_name }} {{ data.last_name }}
                                                                {% else %}
                                                                    {{data.username}}
                                                                {% endif %}
                                                                    </a>
                                                            {% endif %}
                                                        </h6>
                                                        <p class="text-muted m-b-0">
                                                            {% if data.profile.user_type == 'talent' %}
                                                            {% for data in data.talent_set.all %}
                                                                {{data.profession}}
                                                            {% endfor %}
                                                        {% elif  data.profile.user_type == 'startup' %}
                                                            {% for data in data.startup_set.all %}
                                                                 {{ data.category }}
                                                            {% endfor %}
                                                        {% endif %}
                                                        </p>
                                                    </div>
                                                </div>
                                            </td>
                                            <td>{{data.profile.user_type|capfirst}}</td>
                                            {% if data.profile.user_type == 'talent' %}
                                                {% for data in data.talent_set.all %}
                                                    <td> {% include 'includes/rating_for_list_view.html' %}</td>
                                                {% endfor %}
                                            {% elif  data.profile.user_type == 'startup' %}
                                                {% for data in data.startup_set.all %}
                                                    <td> {% include 'includes/rating_for_list_view.html' %}</td>
                                                {% endfor %}
                                            {% endif %}
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                  
                                </table>
                                <nav aria-label="Page navigation example" class="ml-3">
                                    {% if follows.has_other_pages %}
                                        <ul class="pagination">
                                            {% if follows.has_previous %}
                                                <li class="page-item">
                                                    <a class="page-link text-dark" href="?page={{ follows.previous_page_number }}" aria-label="Previous">
                                                    <span aria-hidden="true">prev</span>
                                                    </a>
                                                </li>
                                            {% else %}
                                            <li class="page-item disabled text-center"></li>
                                            {% endif %}
            
                                            {% for i in follows.paginator.page_range %}
                                                {% if follows.number == i %}
                                                    <li class="page-item "><a class="page-link bg-warning text-dark" href="?page={{i}}">{{ i }}</a></li>
                                                {% else %}
                                                    <li class="page-item"><a class="page-link text-dark" href="?page={{i}}">{{ i }}</a></li>
                                                {% endif %}
                                            {% endfor %}
            
                                            {% if follows.has_next %}
                                                <li class="page-item">
                                                    <a class="page-link text-dark" href="?page={{ follows.next_page_number }}" aria-label="Next">
                                                    <span aria-hidden="true">Next</span>
                                                    </a>
                                                </li>
                                            {% else %}
                                            <li class="page-item disabled text-center"></li>
                                            {% endif %}
                                        </ul>
                                    {% endif %}
                                  </nav>
                            </div>
                        </div>
                    </div>
                  </div>
              </div>
                   
            </div>
          
        </div>
    </div>
        <!-- Page-body end -->
</div>
<div id="styleSelector"></div>  
{% endblock contents %}

templates/dash/passwordChange.html
{% extends 'dash/main.html' %}

{% load static %}

{% block contents %}

<div class="pcoded-inner-content">
    <!-- Main-body start -->
    <div class="main-body">
        <div class="page-wrapper">
            <!-- Page-body start -->
            <div class="page-body">
              <div class="row">
                  <div class="col-md-7">
                    {% for field in form %}
                    {% if field.errors %}
                    <div id="noto" class=" text-white text-center alert alert-danger bg-danger alert-dismissible fade show" role="alert">
                        {{ field.errors|striptags }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    {% endif %}
                {% endfor %}
                    <div class="card table-card">
                        <div class="card-header">
                            <h5>Password Change Form</h5>
                            <div class="card-header-right">
                                <ul class="list-unstyled card-option">
                                    <li><i class="fa fa fa-wrench open-card-option"></i></li>
                                    <li><i class="fa fa-window-maximize full-card"></i></li>
                                    <li><i class="fa fa-minus minimize-card"></i></li>
                                    <li><i class="fa fa-refresh reload-card"></i></li>
                                    <li><i class="fa fa-trash close-card"></i></li>
                                </ul>
                            </div>
                        </div>
                        <div class="card-block">
                            <form method="post" class="ml-4" >
                                {% csrf_token %}
                                <div class="row mb-2">
                                    <div class="col-md-6">
                                        <label class="font-weight-bold" for="">Old Password</label>
                                        <input class="form-control" type="password" name="old_password" id="id_old_passsword">
                                    </div>
                                </div>
                                    <div class="row mb-2">
                                        <div class="col-md-6">
                                            <label class="font-weight-bold" for="">New Password</label>
                                            <input class="form-control" type="password" name="new_password1" id="id_new_passsword1">
                                        </div>
                                    </div>
                                    <div class="row mb-2">
                                        <div class="col-md-6">
                                            <label class="font-weight-bold" for="">Confirm Password</label>
                                            <input class="form-control" type="password" name="new_password2" id="id_new_passsword2">
                                        </div>
                                    </div>
                                    
                                </div>
                                <div class="row ml-2">
                                    <div class="col-md-4">
                                        <button type="submit" class="btn btn-warning btn-lg mb-20" >Change Now</button>
                                    </div>
                                </div>
                                <div class="mb-4"></div>
                            </form>
                        </div>
                    </div>
                  </div>
              </div>
                   
            </div>
          
        </div>
    </div>
        <!-- Page-body end -->
</div>
<div id="styleSelector"></div>  
{% endblock contents %}