home/urls.py
from unicodedata import name
from django.urls import path
from . import views


urlpatterns = [
    path('home', views.home, name='home'),
    path('about', views.about,name='about'),
    path('contacts', views.contacts,  name='contacts'),
    path('', views.landing, name='landing' ),
    path('lms', views.lms_home, name='lms'),
    path('terms', views.terms_conditions, name='terms'),
    path('policy', views.privacy_policy, name='policy'),
    path('watchlist', views.watchlist, name="watchlist"),
    path('how-it-works', views.how_it_works, name="how_it_works"),
    path('post-project', views.post_project, name="post_project")
    
]

sandbox/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

handler404 = 'home.views.handler404'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),
    path('', include('home.urls')),
    path('', include('talents.urls')),
    path('', include('startups.urls')),
    path('', include('opportunity.urls')),
    path('', include('userauth.urls')),
    path('', include('dashboard.urls')),

    #social logins url
    # path('oauth/', include('social_django.urls', namespace='social')), 


    path('password-reset/',auth_views.PasswordResetView.as_view(
        template_name='auth/password_reset.html'),name='password_reset'),

    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(
        template_name='auth/password_reset_done.html'),name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(
        template_name='auth/password_reset_confirm.html'),name='password_reset_confirm'),

    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='auth/password_reset_complete.html'), name="password_reset_complete"),
]



if settings.DEBUG:
    urlpatterns += static(
         settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

talents/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from django.utils.text import slugify
from hitcount.models import  HitCount
from django.contrib.contenttypes.fields import GenericRelation
import dashboard



# Create your models here.


SECTORS = (
    ('Architecture & Construction','Architecture & Construction'),
    ('Accountancy and Financial Management','Accountancy and Financial Management'),
    ('Business, Consulting and Management','Business, Consulting and Management '),
    ('Law and Legal Services','Law and Legal Services'),
    ('Non Government Organization','Non Government Organization '),
    ('Media and Communications','Media and Communications'),
    ('Creative Arts and Design','Creative Arts and Design'),
    ('Energy and Utilities','Energy and Utilities'),
    ('Engineering and Manufacturing','Engineering and Manufacturing'),
    ('Agribusiness','Agribusiness'),
    ('Medical and Healthcare','Medical and Healthcare'),
    ('Information Technology','Information Technology'),
    ('Hospitality and Tourism','Hospitality and Tourism'),
    ('Marketing, Advertising and PR','Marketing, Advertising and PR'),
    ('Sales','Sales'),
    ('Real Estate','Real Estate'),
    ('Finance, Retail and Banking Services','Finance, Retail and Banking Services'),
    ('Office Management and Human Resources Services','Office Management and Human Resources Services'),
    ('Transportation, Distribution & Logistics','Transportation, Distribution & Logistics')
)

WORK_EXP =(
    ('Less than 1 Year', 'Less than 1 Year'),
    ('2-5 years','2-5 years'),
    ('5-7 years','5-7 years'),
    ('7-10 years', '7-10 years'),
    ('10 years and above', '10 years and above')      
)
GENDER = (
    ('male','male'),
    ('female','female'),
)
JOB_CATEGORIES = (
    ('full time', 'full time'),
    ('remote', 'remote'),
    ('contractual','contractual'),
    ('internship','internship'),
    ('voluntering', 'voluntering'),
    ('freelance','freelance'),
    ('part-time','part-time'),
    ('temporary', 'temporary'),
    ('internship','internship')
)


class Talent(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    views = models.ManyToManyField(User, related_name="views", blank=True)
    profession  = models.CharField(max_length=100)
    about = models.TextField()
    category = models.CharField(max_length=100, choices=SECTORS)
    years_of_experience = models.CharField(max_length=100, choices=WORK_EXP)
    dob = models.DateTimeField(default=datetime.now)
    gender = models.CharField(max_length=10, choices=GENDER)
    languages = models.CharField(max_length=100)
    salary_expectation = models.CharField(max_length=100)
    prefered_work_type = models.CharField(max_length=100,choices=JOB_CATEGORIES)
    phone = models.CharField(max_length=10)
    location = models.CharField(max_length=100)
    linkedIn = models.URLField(null=True, blank=True)
    slug = models.SlugField(default=User, unique=True)
    hit_count_generic = GenericRelation(HitCount, object_id_field='object_pk',
     related_query_name='hit_count_generic_relation')

    

    def save(self, *args, **kwargs):
        self.slug = slugify(self.user.username)
        super(Talent, self).save(*args, **kwargs)

    @property
    def get_skills(user):
        skills = Skill.objects.filter(talent=user)
        return skills
    
    
    @property
    def get_experience(user):
        exp = Experience.objects.filter(talent=user)
        return exp
    
    @property
    def get_education(user):
        edu = Education.objects.filter(talent=user)
        return edu
    
    @property
    def get_award(user):
        awd = Award.objects.filter(talent=user)
        return awd

    
    @property
    def get_rating(self):
        rating =dashboard.models.Rating.objects.filter(rating_for=self.id)

        sum_of_user_rates =  sum(rating.values_list('rating_value', flat=True)) # --> rating for one user filtered above

        all_ratings_to_talent = rating.count()  * 5 # --> getting number of all ratings for a filtered user
        try:
            rates= round(sum_of_user_rates * 5 / all_ratings_to_talent, 1)
        except ZeroDivisionError:
            rates = 0
        return rates

    def __str__(self):
        return self.user.username



# def create_talent(sender, **kwargs):
#     if kwargs['created']:
#        talent = Talent.objects.create(user=kwargs['instance'])
       
# post_save.connect(create_talent, sender=User)


class Experience(models.Model):
    WORKING = (
        ('No','No'),
        ('Yes',"Yes")
    )
    talent = models.ForeignKey(Talent, on_delete=models.CASCADE)
    company_name =  models.CharField(max_length=100)
    start_date = models.DateTimeField(default=datetime.now)
    finish_date = models.DateTimeField(null=True, blank=True)
    still_working = models.CharField(max_length=100, null=True,blank=True, choices=WORKING)
    position = models.CharField(max_length=100)
    details = models.TextField()

    def __str__(self):
        return str(self.talent)


class Education(models.Model):
    talent = models.ForeignKey(Talent, on_delete=models.CASCADE)
    speciality =  models.CharField(max_length=100)
    start_date = models.DateTimeField(default=datetime.now)
    end_date = models.DateTimeField(max_length=100)
    school_name = models.CharField(max_length=100)
    details = models.TextField()

    def __str__(self):
        return str(self.talent)
    
    class Meta:
        verbose_name_plural = 'Education'
    

class Award(models.Model):
    talent = models.ForeignKey(Talent, on_delete=models.CASCADE)
    name =  models.CharField(max_length=100)
    awarded_on = models.DateTimeField(default=datetime.now)
    details = models.TextField()

    def __str__(self):
        return str(self.talent)

class Skill(models.Model):
    talent = models.ForeignKey(Talent, on_delete=models.CASCADE)
    skill = models.CharField(max_length=100)
    experience = models.CharField(max_length=100, null=True,blank=True)

    def __str__(self):
        return str(self.talent)

templates/talent_dash/alerts.html
{% extends 'base.html' %}
{% load social_share %}
{% load static %}


{% block title %}
    <title>Plumar | Alerts</title>
{% endblock title %}

{% block header %}
{% endblock header %}

{% block contents %}
{% include 'includes/nav.html' %}
<style>
    .btnz{
        height: 22px;
        font-size: 13px;
        margin-top: 15px;
    }
</style>
        <!-- Dashboard Content Section Start -->
        <div class="dashboard-content-section section bg_color--5">
            <div class="container-fluid p-0">
                <div class="row no-gutters">
                    <div class="col-xl-2 col-lg-3">
                        {% include 'talent_dash/includes/sidebar.html' %}
                    </div>
                    <div class="col-xl-10 col-lg-9">

                        <div class="dashboard-main-inner">
                            <div class="row">
                                <div class="col-4">
                                    <div class="page-breadcrumb-content mb-40">
                                        <h1>Recent Opportunities</h1>
                                    </div>
                                </div>
                                <div class="col-7">
                                    {% if messages %}
                                        {% for message in messages %}
                                            {% if message.tags == 'success' %}
                                                <div  id="noto" class="alert alert-success"><i class="bi bi-check-circle"></i> 
                                                    {{ message }}
                                                </div>
                                            {% endif %}
                                            {% if message.tags == 'error' %}
                                                <div id="noto" class="alert alert-danger bg-danger alert-dismissible fade show ">
                                                    <span class="text-white" >{{ message }}</span>
                                                </div>
                                            {% endif %}
                                        {% endfor %}
                                    {% endif %}
                                </div>
                            </div>
                            <div class="dashboard-overview">
                                <div class="row">
                                    <div class="col-xl-12 col-12">
                                        <div class="job-applications mb-50">
                                            <!-- <div class="profile-applications-heading">
                                                <ul class="nav">
                                                    <li><a class="active" href="profile.html">My profile</a></li>
                                                    <li><a href="resume-profile.html">Resume profile</a></li>
                                                </ul>
                                            </div> -->
                                            <div class="job-applications-main-block">
                                                <div class="job-applications-table">
                                                    <table class="table">
                                                        <thead>
                                                            <tr>
                                                                <th>Alert Title</th>
                                                                <th class="width-35">Link</th>
                                                                <th>Created</th>
                                                                <!-- <th>Update</th> -->
                                                                
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            {% for data in opps|slice:"5" %}
                                                            <tr class="job-application-item">
                                                                <td class="application-job">
                                                                    <h3><a href="#">{{ data.title }}</a></h3>
                                                                </td>
                                                
                                                                <td class="application-query">
                                                                    <a class="text-warning"  href="{% url 'opp_details' data.id %}">plumar.co/opportunity/{{ data.id }}</a>
                                                                </td>
                                                
                                                                <td class="application-created">
                                                                    <span> {{data.date_published|date:"M d, Y"}} </span>
                                                                </td>
                                                
                                                                <!-- <td class="application-update">
                                                                    <span> Weekly </span>
                                                                </td> -->
                                                
                                                            </tr>
                                                            {% endfor %}
                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Dashboard Content Section End -->







    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" ></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" ></script>
    <script>
        $('#noto').delay(5000).fadeOut('slow');
    </script>

    {% endblock contents %}

 
    {% block footer %}
    {% endblock footer %}
    

templates/talent_dash/education.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    <title>Plumar | Education</title>
{% endblock title %}

{% block header %}
{% endblock header %}

{% block contents %}
{% include 'includes/nav.html' %}
<style>
    #id_still_working li{
        display: inline-flex;
        margin-left: 20px;
        
        justify-content: space-between;
    }
    /* input[type="radio"]{margin: 0px 20px}; */
</style>

        <!-- Dashboard Content Section Start -->
        <div class="dashboard-content-section section bg_color--5">
            <div class="container-fluid p-0">
                <div class="row no-gutters">
                    <div class="col-xl-2 col-lg-3">
                        {% include 'talent_dash/includes/sidebar.html' %}
                    </div>
                    <div class="col-xl-10 col-lg-9">

                        <div class="dashboard-main-inner">
                            <div class="row">
                                <div class="col-4">
                                    <div class="page-breadcrumb-content mb-40">
                                        <h1>Education Information</h1>
                                    </div>
                                </div>
                                <div class="col-7">
                                    {% if messages %}
                                        {% for message in messages %}
                                            {% if message.tags == 'success' %}
                                                <div  id="noto" class="alert alert-success"><i class="bi bi-check-circle"></i> 
                                                    {{ message }}
                                                </div>
                                            {% endif %}
                                            {% if message.tags == 'error' %}
                                                <div id="noto" class="alert alert-danger bg-danger alert-dismissible fade show ">
                                                    <span class="text-white" >{{ message }}</span>
                                                </div>
                                            {% endif %}
                                        {% endfor %}
                                    {% endif %}
                                </div>
                            </div>
                            <div class="dashboard-overview">
                                <div class="row">
                                    <div class="col-xl-12 col-12">
                                        <div class="profile-applications mb-50">
                                            <!-- <div class="profile-applications-heading">
                                                <ul class="nav">
                                                    <li><a class="active" href="profile.html">My profile</a></li>
                                                    <li><a href="resume-profile.html">Resume profile</a></li>
                                                </ul>
                                            </div> -->
                                            <div class="profile-applications-main-block">
                                                <div class="profile-applications-form">
                                                    {% for data in education %}
                                                    <div class="row mb-20">
                                                        <div class="col-lg-4 col-md-4">
                                                            <div class="content-left">
                                                                <h5 class="company-name theme-color">
                                                                    <i class="fas fa-school text-muted" ></i> {{data.school_name}} 
                                                                </h5>
                                                                <span>
                                                                    <i class="lnr lnr-graduation-hat text-muted" ></i> {{ data.speciality }}
                                                                </span>
                                                               
                                                            </div>
                                                            <span class="date">
                                                                <i class="lnr lnr-clock" ></i> {{data.start_date|date:'m/Y'}} - {{ data.end_date|date:"m/Y"}}
                                                            </span>
                                                            
                                                        </div>
                                                        <div class="col-lg-6 col-md-6">
                                                            {{data.details}}
                                                        </div>
                                                        <div class=" col-lg-2 col-md-2">
                                                            <a data-bs-toggle="modal" data-bs-target=".edit{{data.id}}"  data-bs-placement="bottom" title="Edit"><i class="lnr lnr-pencil" ></i></a>
                                                            <a data-bs-target="#delete{{ data.id }}" data-bs-toggle="modal" data-bs-placement="bottom" title="Delete"><i class="fa fa-trash ml-4" ></i></a>
                                                        </div>
                                                    </div>
                                                    {% endfor %}
                                                    <button class="btn btn-warning mt-3"data-bs-toggle="modal" data-bs-target="#staticBackdrop" >Add Education Background</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Dashboard Content Section End -->


          <!-- Modal -->
  <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel">Add Education Information</h5>
          <a type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">&#10006;</a>
        </div>
        <div class="modal-body">
            <form action="{% url 'education' %}" method="post">
                {% csrf_token %}
                <div class="row mb-20">
                    <div class="col-md-6">
                        <label for="">Programme/Speciality/Course</label>
                        <input type="text" name="speciality" class="form-control">
                    </div>
                    <div class="col-md-6">
                        <label for="">School/university/College Name</label>
                        <input type="text" name="school_name" class="form-control">
                    </div>
                </div>
                <div class="row mb-20">
                    <div class="col-md-6">
                        <label for="">Start Date</label>
                        <input type="date" name="start_date" class="form-control">
                    </div>
                    <div class="col-md-6">
                        <label for="">End Date</label>
                        <input type="date" name="end_date" class="form-control">
                    </div>
                </div>
                <div class="row mb-20">
                    <div class="col-md-12">
                        <label for="">Describe Your Experience During Your Studies</label>
                        <textarea class="form-control" name="details" id="" cols="30" rows="5"></textarea>
                    </div>
    
                </div>
                </div>
                <div class="row ml-2 mr-2">
                    

                </div>
                <div class="ml-4 mt-3 mb-20">
                    <button type="submit" class="btn btn-warning">Submit Now</button>
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
            </form>
        </div>
       
      </div>
    </div>



    {% for data in education %}
    <div class="modal fade edit{{data.id}} "  data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title font-weight-bold" id="staticBackdropLabel">{{data.school_name}}</h5>
              <a type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">&#10006;</a>
            </div>
            <div class="modal-body" >
                <form action="/edit-education/{{ data.id }}" method="post" enctype="multipart/form-data" >
                    {% csrf_token %}
                    <div class="row mb-20">
                        <div class="col-md-6">
                            <label for="">Programme/Speciality/Course</label>
                           <input type="text" class="form-control" name="speciality" value="{{data.speciality}}" > 
                        </div>
                        <div class="col-md-6">
                            <label for="">School/university/College Name</label>
                            <input type="text" class="form-control" name="school_name" value="{{data.school_name}}" >
                        </div>
                    </div>
                    <div class="row mb-20">
                        <div class="col-md-6">
                            <label for="">Start Date</label>
                            <input type="date" class="form-control" name="start_date" value="{{data.start_date|date:'Y-m-d'}}" >
                        </div>
                       
                        <div class="col-md-6">
                            <label for="">End Date</label>
                            <input id="fin" type="date" class="form-control" name="end_date" value="{{data.end_date|date:'Y-m-d'}}" >
                        </div>
                    </div>
                    <div  class="row mb-20">
                        <div class="col-md-12">
                            <label for="">Describe Your Experience During Your Studies</label>
                            <textarea class="form-control"  cols="30" rows="5" name="details" >{{data.details}}</textarea>
                        </div>
                    </div>
                    
                    
                </div>
                <div class="ml-4 mt-3 mb-20">
                    <button type="submit" class="btn btn-warning text-white">Submit</button>
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
            </form>
               
          </div>
        </div>
    </div>
    {%  endfor%}



    {% for data in education %}
    <div class="modal fade" id="delete{{ data.id }}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="staticBackdropLabel">Delete Experince</h5>
              <a type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">&#10006;</a>
            </div>
            <div class="modal-body">
                <span class="text-danger font-weight-bold" >
                    Are you sure you want to delete this data?
                </span>
            </div>
            <div class="ml-4 mt-3 mb-20">
                <a href="{% url 'delete_education' data.id %}" class="btn btn-danger text-white">Delete</a>
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
    </div>
    {% endfor %}





    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" ></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" ></script>
    <script>
        $('#noto').delay(5000).fadeOut('slow');
    </script>

    {% endblock contents %}

 
    {% block footer %}
    {% endblock footer %}
    